### PR TITLE
Upgrade sly to 0.5

### LINKED ISSUE #35: Please add support for sly==0.5.0
Please see our "Development Speed" note in the README.md of the project for expected response times. 

Thanks for the feature request! Here's some guidance to get you started on what we are looking for in terms of details:

**Is your feature request related to a problem? Please describe.**
We are a Linux distro and can only ever ship one version of a python package.

We recently updated sly from 0.4 to 0.5 and `test_command_line` has started breaking.

```
scim2-filter-parser> Executing unittestCheckPhase
scim2-filter-parser> ............................F..........................................................................................................................................
scim2-filter-parser> ======================================================================
scim2-filter-parser> FAIL: test_command_line (tests.test_lexer.CommandLine)
scim2-filter-parser> ----------------------------------------------------------------------
scim2-filter-parser> Traceback (most recent call last):
scim2-filter-parser>   File "/build/source/tests/test_lexer.py", line 449, in test_command_line
scim2-filter-parser>     self.assertEqual(result, expected)
scim2-filter-parser> AssertionError: Lists differ: ["Tok[50 chars]dex=0, end=8)", "Token(type='EQ', value='eq', [96 chars]21)"] != ["Tok[50 chars]dex=0)", "Token(type='EQ', value='eq', lineno=[73 chars]12)"]
scim2-filter-parser> 
scim2-filter-parser> First differing element 0:
scim2-filter-parser> "Token(type='ATTRNAME', value='userName', lineno=1, index=0, end=8)"
scim2-filter-parser> "Token(type='ATTRNAME', value='userName', lineno=1, index=0)"
scim2-filter-parser> 
scim2-filter-parser> - ["Token(type='ATTRNAME', value='userName', lineno=1, index=0, end=8)",
scim2-filter-parser> ?                                                             -------
scim2-filter-parser> 
scim2-filter-parser> + ["Token(type='ATTRNAME', value='userName', lineno=1, index=0)",
scim2-filter-parser> -  "Token(type='EQ', value='eq', lineno=1, index=9, end=11)",
scim2-filter-parser> ?                                                 --------
scim2-filter-parser> 
scim2-filter-parser> +  "Token(type='EQ', value='eq', lineno=1, index=9)",
scim2-filter-parser> -  "Token(type='COMP_VALUE', value='bjensen', lineno=1, index=12, end=21)"]
scim2-filter-parser> ?                                                               --------
scim2-filter-parser> 
scim2-filter-parser> +  "Token(type='COMP_VALUE', value='bjensen', lineno=1, index=12)"]
scim2-filter-parser> 
scim2-filter-parser> ----------------------------------------------------------------------
scim2-filter-parser> Ran 167 tests in 0.104s
scim2-filter-parser> 
scim2-filter-parser> FAILED (failures=1)
```

**Describe the solution you'd like**
Make the package compatible with `sly==0.5`

**Describe alternatives you've considered**
Unfortunately we can only disable the package or leave it in a broken state.

**Additional context**
n/a

cc @s1341

### PR DESCRIPTION
**Pull request by logston**
This commit upgrades sly to 0.5. This is the last version of sly that will be published to PyPI per the author of that library. Future versions of sly will only contain bug fixes.

Closes #35.

### CODE REVIEW

**Comment by logston** [comment]
@markendev @bartoszgrabski Looks like I've lost admin permissions on this repo and I need those to fix the failing tests.

https://github.com/orgs/community/discussions/26698#discussioncomment-3252954

Can I be re-granted admin permissions on this repo? Hope you both are well.

**Comment by logston** [comment]
We should merge https://github.com/15five/scim2-filter-parser/pull/37 first before this PR.

**Comment by bartoszgrabski** [comment]
@logston Hi Paul! I'm doing well, how about you?

I re-granted you Admin role in this repo 👍

**Comment by logston** [comment]
Thank you @bartoszgrabski! I am well as well :)

**Comment by logston** [comment]
Hi @bartoszgrabski, all the test are passing on this PR sans a review. Thus I've made you a reviewer. I also just pushed a version of this repo for tag 0.4.2 to PyPI.

**Review by bartoszgrabski — APPROVED** [review]

**Review by markendev — APPROVED** [review]

**Comment by logston** [comment]
TFTR!

**Pull request merged**
